# Site settings
title: Meng Chen
email: chenmengdx@gmail.com
description: 
  Time is the only critic without ambition. - John Steinbeck
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chenmengdx.github.io" # the base hostname & protocol for your site
twitter_username: chenmengdx
github_username:  chenmengdx

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Research Scientist"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
